services:
  # Backend API Service
  - type: web
    name: iwanyu-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npx prisma generate && npx prisma migrate deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: iwanyu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://iwanyu-2-0.vercel.app
      - key: CORS_ORIGIN
        value: https://iwanyu-2-0.vercel.app
      - key: FLUTTERWAVE_PUBLIC_KEY
        value: FLWPUBK-80beae9a1e1463654d41a8e4d00515dd-X
      - key: FLUTTERWAVE_SECRET_KEY
        value: FLWSECK-cc842f4c47bf0059d3854bf053c11296-1973d2d141dvt-X
      - key: FLUTTERWAVE_ENCRYPTION_KEY
        value: cc842f4c47bf3f882628801e
    rootDir: backend

  # PostgreSQL Database
  - type: pgsql
    name: iwanyu-db
    plan: free
    databaseName: iwanyu
    user: iwanyu
