services:
  # Backend API Service
  - type: web
    name: iwanyu-backend
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: iwanyu-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://iwanyu-frontend.vercel.app
      - key: CORS_ORIGIN
        value: https://iwanyu-frontend.vercel.app
    rootDir: backend

  # PostgreSQL Database
  - type: pgsql
    name: iwanyu-db
    plan: free
    databaseName: iwanyu
    user: iwanyu
