version: 2
services:
  - type: web
    name: iwanyu-backend
    env: node
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm run db:migrate && npm start
    plan: starter
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: iwanyu-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://iwanyu.vercel.app
      - key: ALLOWED_ORIGINS
        value: https://iwanyu.vercel.app,https://your-custom-domain.com

databases:
  - name: iwanyu-postgres
    databaseName: iwanyu
    user: iwanyu_user
    plan: starter
